constructor {
  New : ();
};

service ContractService {
  Decrement : () -> u64;
  GetValue : (to_return: u128) -> str;
  Hello : () -> str;
  Increment : () -> u64;
  SendValue : () -> str;
  query CounterValue : () -> u64;

  events {
    Hello: actor_id;
    ValueReceived: u128;
    ValueSent: u128;
    Incremented;
    Decremented;
  }
};

