// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ContractClientProgram;
impl sails_rs::client::Program for ContractClientProgram {}
pub trait ContractClient {
    type Env: sails_rs::client::GearEnv;
    fn contract_service(
        &self,
    ) -> sails_rs::client::Service<contract_service::ContractServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClient
    for sails_rs::client::Actor<ContractClientProgram, E>
{
    type Env = E;
    fn contract_service(
        &self,
    ) -> sails_rs::client::Service<contract_service::ContractServiceImpl, Self::Env> {
        self.service(stringify!(ContractService))
    }
}
pub trait ContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClientCtors
    for sails_rs::client::Deployment<ContractClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod contract_service {
    use super::*;
    pub trait ContractService {
        type Env: sails_rs::client::GearEnv;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env>;
        fn get_value(
            &mut self,
            to_return: u128,
        ) -> sails_rs::client::PendingCall<io::GetValue, Self::Env>;
        fn hello(&mut self) -> sails_rs::client::PendingCall<io::Hello, Self::Env>;
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env>;
        fn send_value(&mut self) -> sails_rs::client::PendingCall<io::SendValue, Self::Env>;
        fn counter_value(&self) -> sails_rs::client::PendingCall<io::CounterValue, Self::Env>;
    }
    pub struct ContractServiceImpl;
    impl<E: sails_rs::client::GearEnv> ContractService
        for sails_rs::client::Service<ContractServiceImpl, E>
    {
        type Env = E;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env> {
            self.pending_call(())
        }
        fn get_value(
            &mut self,
            to_return: u128,
        ) -> sails_rs::client::PendingCall<io::GetValue, Self::Env> {
            self.pending_call((to_return,))
        }
        fn hello(&mut self) -> sails_rs::client::PendingCall<io::Hello, Self::Env> {
            self.pending_call(())
        }
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env> {
            self.pending_call(())
        }
        fn send_value(&mut self) -> sails_rs::client::PendingCall<io::SendValue, Self::Env> {
            self.pending_call(())
        }
        fn counter_value(&self) -> sails_rs::client::PendingCall<io::CounterValue, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Decrement () -> u64);
        sails_rs::io_struct_impl!(GetValue (to_return: u128) -> String);
        sails_rs::io_struct_impl!(Hello () -> String);
        sails_rs::io_struct_impl!(Increment () -> u64);
        sails_rs::io_struct_impl!(SendValue () -> String);
        sails_rs::io_struct_impl!(CounterValue () -> u64);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ContractServiceEvents {
            Hello(ActorId),
            ValueReceived(u128),
            ValueSent(u128),
            Incremented,
            Decremented,
        }
        impl sails_rs::client::Event for ContractServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "Hello",
                "ValueReceived",
                "ValueSent",
                "Incremented",
                "Decremented",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ContractServiceImpl {
            type Event = ContractServiceEvents;
        }
    }
}

#[cfg(feature = "with_mocks")]
#[cfg(not(target_arch = "wasm32"))]
extern crate std;

#[cfg(feature = "with_mocks")]
#[cfg(not(target_arch = "wasm32"))]
pub mod mockall {
    use super::*;
    use sails_rs::mockall::*;
    mock! { pub ContractService {} #[allow(refining_impl_trait)] #[allow(clippy::type_complexity)] impl contract_service::ContractService for ContractService { type Env = sails_rs::client::GstdEnv; fn decrement (&mut self, ) -> sails_rs::client::PendingCall<contract_service::io::Decrement, sails_rs::client::GstdEnv>;fn get_value (&mut self, to_return: u128) -> sails_rs::client::PendingCall<contract_service::io::GetValue, sails_rs::client::GstdEnv>;fn hello (&mut self, ) -> sails_rs::client::PendingCall<contract_service::io::Hello, sails_rs::client::GstdEnv>;fn increment (&mut self, ) -> sails_rs::client::PendingCall<contract_service::io::Increment, sails_rs::client::GstdEnv>;fn send_value (&mut self, ) -> sails_rs::client::PendingCall<contract_service::io::SendValue, sails_rs::client::GstdEnv>;fn counter_value (& self, ) -> sails_rs::client::PendingCall<contract_service::io::CounterValue, sails_rs::client::GstdEnv>; } }
}
